SklepInternetowy/Controllers/ShoppingHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SklepInternetowy.DatabaseManager;
using SklepInternetowy.Entities;

namespace SklepInternetowy.Controllers
{
    public class ShoppingHistoryController : Controller
    {
        private readonly DBManager _dBManager;
        public ShoppingHistoryController(DBManager dBManager)
        {
            _dBManager = dBManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Route("ShoppingHistory/{id}")]
        public IActionResult Details(int id)
        {

            return View(_dBManager._dbContext.ShoppingHistories.Where(x => x.Id == id).FirstOrDefault());
        }
    }
}

SklepInternetowy/Views/ShoppingHistory/Details.cshtml
@using SklepInternetowy.Entities
@{
    ShoppingHistoryEntity history = Model;
    int random_number = new Random().Next(1, 5);
    string progress = "c"+ random_number;
}



<link rel="stylesheet" href="~/css/shoppingHistory.css" />
<div class="order-status">

    <div class="order-status-timeline">
        <div class="order-status-timeline-completion @progress"></div>
    </div>

    <div class="image-order-status image-order-status-new active img-circle">
        <span class="status">Accepted</span>
        <div class="icon"></div>
    </div>
    <div class="image-order-status image-order-status-active active img-circle">
        <span class="status">In progress</span>
        <div class="icon"></div>
    </div>
    <div class="image-order-status image-order-status-intransit active img-circle">
        <span class="status">Shipped</span>
        <div class="icon"></div>
    </div>
    <div class="image-order-status image-order-status-delivered active img-circle">
        <span class="status">Delivered</span>
        <div class="icon"></div>
    </div>
    <div class="image-order-status image-order-status-completed active img-circle">
        <span class="status">Completed</span>
        <div class="icon"></div>
    </div>

</div>

SklepInternetowy/Views/ShoppingHistory/Index.cshtml
@using SklepInternetowy.DatabaseManager
@inject DBManager Manager

<style>
    a {
        text-decoration: none;
    }
</style>
<div class="container py-5">
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <ul class="list-group shadow">

                @foreach (var shoppingHistory in Manager.GetShoppingHistory())
                {
                    <a asp-controller="ShoppingHistory" asp-route-id="@shoppingHistory.Id" asp-action="Details">
                        <li class="list-group-item">
                            <div class="media align-items-lg-center flex-column flex-lg-row p-3">
                                <div class="media-body order-2 order-lg-1">
                                    @foreach (var item in Manager.GetUserShoppingCartItems(shoppingHistory.ShoppingCart).Select(x => x.Product.Name))
                                    {
                                        @item
                                        <br />
                                    }
                                </div><div class="ml-lg-5 order-1 order-lg-2"><i class="fas fa-truck fa-4x"></i></div>
                            </div>
                        </li>
                    </a>
                }
            </ul>
        </div>
    </div>
</div>