SklepInternetowy/Controllers/FavoriteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace SklepInternetowy.Controllers
{
    public class FavoriteController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SklepInternetowy/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SklepInternetowy.DatabaseManager;
using SklepInternetowy.Models;

namespace SklepInternetowy.Controllers
{
    public class ProductController : Controller
    {
        private readonly DBManager _dBManager;
        public ProductController(DBManager dBManager)
        {
            _dBManager = dBManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            return View(id);
        }
    }
}

SklepInternetowy/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SklepInternetowy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/login.css" />
    <link rel="stylesheet" href="~/css/products.css" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Strona główna</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Produkty</a>
                        </li>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="#" id="showModal">Zaloguj się</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingHistory" asp-action="Index">Moje zakupy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Favorite" asp-action="Index">Ulubione</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="#" id="logout">Wyloguj się</a>
                            </li>
                            <li class="nav-item px-2 text-uppercase mt-2 position-relative d-lg-fle">
                                <a asp-area="" asp-controller="ShoppingCart" asp-action="Index" class="cart position-relative d-inline-flex" aria-label="View your shopping cart">
                                    <i class="fas fa fa-shopping-cart fa-lg"></i>
                                    <span class="cart-basket d-flex align-items-center justify-content-center">
                                        <vc:shopping-cart-items-count />
                                    </span>
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="alert" style="display:none;">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        <div class="errorMessage">

        </div>
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @if (!User.Identity.IsAuthenticated)
            {
                <partial name="_LoginRegisterPartial" />
            }

            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SklepInternetowy
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/auth.js" asp-append-version="true"></script>
    <script src="~/js/product.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SklepInternetowy/Views/Shared/_LoginRegisterPartial.cshtml
<div class="modal login-container" id="loginForm">
    <div class="row justify-content-md-center">
        <div class="col-md-4 login-form-1">
            <form id="SignIn">
                <h3>Sign in</h3>
                <div class="form-group">
                    <input type="text" class="form-control" name="username" value="test123" placeholder="Username *" />
                    <div style="font-size:12px;" class="error text-warning"></div>
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="password" value="test123" placeholder="Your Password *" />
                    <div style="font-size:12px;" class="error text-warning"></div>
                </div>
                <div class="form-group">
                    <input type="submit" class="btnSubmit" value="Login" />
                </div>
            </form>
            <div id="signin-errors" style="display:none;" class="alert alert-danger" role="alert">
            </div>
        </div>
        <div class="col-md-4 login-form-2">
            <form id="SignUp">
                <h3>Sign up</h3>
                <div class="form-group">
                    <input type="text" class="form-control" name="regusername" placeholder="Username *" />
                    <div style="font-size:12px;" class="error text-warning"></div>
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="name" placeholder="Name *" />
                    <div style="font-size:12px;" class="error text-warning"></div>
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="lastname" placeholder="Lastname *" />
                    <div style="font-size:12px;" class="error text-warning"></div>
                </div>
                <div class="form-group">
                    <input type="email" class="form-control" name="email" placeholder="Your Email *" />
                    <div style="font-size:12px;" class="error text-warning"></div>
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="regpassword" placeholder="Your Password *" />
                    <div style="font-size:12px;" class="error text-warning"></div>
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="passwordconfirmation" placeholder="Confirm password *" />
                    <div style="font-size:12px;" class="error text-warning"></div>
                </div>
                <div class="form-group">
                    <input type="submit" class="btnSubmit" value="Register" />
                </div>
                <i id="closeModal" class="far fa-window-close"></i>
            </form>
            <div id="signup-errors" style="display:none;" class="alert alert-danger" role="alert">
            </div>
        </div>
    </div>
</div>